---
- name: Server Setup
  hosts: linux
  become: true
  gather_facts: true

  vars:
    admin_user: asur
    guest_user: guest

  roles:
    - user_management
    - auditing
    - security
    - reporting
    - docker_compose
    - navidrome
    - nginx
    - scripts
